package com.stc.inspireu.authorization;

public enum Roles {
    ROLE_STARTUPS_ADMIN, ROLE_STARTUPS_MEMBER, ROLE_EXISTING_STARTUPS, ROLE_NON_STC_JUDGES, ROLE_STC_JUDGES,
    ROLE_SUPER_ADMIN, ROLE_MANAGEMENT_TEAM_ADMIN, ROLE_MANAGEMENT_TEAM_MEMBER, ROLE_COACHES_AND_TRAINERS,
    ROLE_RECEPTIONIST,ROLE_PARTNER
}
