package com.stc.inspireu.services.impl;

import com.stc.inspireu.enums.Constant;
import com.stc.inspireu.enums.EmailKey;
import com.stc.inspireu.models.*;
import com.stc.inspireu.repositories.*;
import com.stc.inspireu.services.InitDataService;
import com.stc.inspireu.utils.PasswordUtil;
import com.stc.inspireu.utils.RoleName;
import lombok.RequiredArgsConstructor;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.util.Date;

@Service
@RequiredArgsConstructor
public class InitDataServiceImpl implements InitDataService {

    private final String minioFileFolder = "files_folders";

    private final String rootFileFolderUID = "oscS1UBIQoRZuFVZtVMRZuFVZ43kqRzkQoRZuFVZtVMRZuFVZ43sbf9";

    @Value("${superadmin.email}")
    private String superadminEmail;

    @Value("${inspireu.fileDir}")
    private String inspireuFileDir;

    @Value("${inspireu.profilePics}")
    private String inspireuProfilePics;

    @Value("${inspireu.management.folder}")
    private String inspireuManagementFolder;

    private final UserRepository userRepository;
    private final RoleRepository roleRepository;
    private final PasswordUtil passwordUtil;
    private final EmailTemplateRepository emailTemplateRepository;
    private final EmailTemplateTypesRepository emailTemplateTypesRepository;
    private final IntakeProgramRepository intakeProgramRepository;

    @Override
    @Transactional
    public void createSuperAdmin(String superadminEmail, String superadminPassword) {
        User user2 = new User();
        Role role = roleRepository.findByRoleName(RoleName.ROLE_SUPER_ADMIN);
        user2.setEmail(superadminEmail);
        user2.setAlias("superadmin");
        user2.setRole(role);
        user2.setEnableEmail(true);
        user2.setEnableWeb(true);
        user2.setIsRemovable(false);
        user2.setWillManagement(true);
        user2.setInvitationStatus(Constant.REGISTERED.toString());
        String hashedPasswordAdmin = passwordUtil.getHashedPassword(superadminPassword);
        user2.setPassword(hashedPasswordAdmin);
        userRepository.save(user2);
    }

    @Transactional
    @Override
    public void createEmailTemplates() {
        if (emailTemplateTypesRepository.count() == 0) {
            User u = userRepository.findByEmail(superadminEmail);
            if (u != null) {
                EmailTemplatesTypes ett1 = new EmailTemplatesTypes();
                ett1.setName(Constant.STARTUP.toString());
                ett1.setStatus(Constant.ACTIVE.toString());
                ett1.setCreatedUser(u);
                ett1.setIconName("icon-startups");
                EmailTemplatesTypes startUp = emailTemplateTypesRepository.save(ett1);
                EmailTemplatesTypes ett2 = new EmailTemplatesTypes();
                ett2.setName(Constant.MANAGEMENT.toString());
                ett2.setStatus(Constant.ACTIVE.toString());
                ett2.setCreatedUser(u);
                ett2.setIconName("icon-admin");
                EmailTemplatesTypes mngt = emailTemplateTypesRepository.save(ett2);
                EmailTemplatesTypes ett3 = new EmailTemplatesTypes();
                ett3.setName(Constant.OTHER.toString());
                ett3.setStatus(Constant.ACTIVE.toString());
                ett3.setCreatedUser(u);
                ett3.setIconName("icon-others");
                EmailTemplatesTypes others = emailTemplateTypesRepository.save(ett3);
                EmailTemplate west = new EmailTemplate();
                west.setKey(EmailKey.welcome_existing_startup.toString());
                west.setContent("<p>welcome_existing_startup</p>");
                west.setCreatedUser(u);
                west.setEmailContentType(Constant.EXSISTING_STARTUP.toString());
                west.setEmailTemplatesTypes(startUp);
                west.setFooter("<p>STC</p>");
                west.setHeader("<p>STC</p>");
                west.setIntakeProgram(null);
                west.setName(EmailKey.welcome_existing_startup.toString());
                west.setStatus(Constant.ACTIVE.toString());
                west.setSubject(EmailKey.welcome_existing_startup.toString());
                west.setLanguage("en");
                emailTemplateRepository.save(west);
                EmailTemplate est = new EmailTemplate();
                est.setKey(EmailKey.invite_existing_startup.toString());
                est.setContent("<p>invite_existing_startup</p>");
                est.setCreatedUser(u);
                est.setEmailContentType(Constant.EXSISTING_STARTUP.toString());
                est.setEmailTemplatesTypes(startUp);
                est.setFooter("<p>STC</p>");
                est.setHeader("<p>STC</p>");
                est.setIntakeProgram(null);
                est.setName(EmailKey.invite_existing_startup.toString());
                est.setStatus(Constant.ACTIVE.toString());
                est.setSubject(EmailKey.invite_existing_startup.toString());
                est.setLanguage("en");
                emailTemplateRepository.save(est);
                EmailTemplate et1 = new EmailTemplate();
                et1.setKey(EmailKey.invite_startup_member.toString());
                et1.setContent("<p>invite_startup_member</p>");
                et1.setCreatedUser(u);
                et1.setEmailContentType(Constant.STARTUPS_MEMBER.toString());
                et1.setEmailTemplatesTypes(startUp);
                et1.setFooter("<p>STC</p>");
                et1.setHeader("<p>STC</p>");
                et1.setIntakeProgram(null);
                et1.setName(EmailKey.invite_startup_member.toString());
                et1.setStatus(Constant.ACTIVE.toString());
                et1.setSubject(EmailKey.invite_startup_member.toString());
                et1.setLanguage("en");
                emailTemplateRepository.save(et1);
                EmailTemplate et2 = new EmailTemplate();
                et2.setKey(EmailKey.invite_startup_admin.toString());
                et2.setContent("<p>invite_startup_admin</p>");
                et2.setCreatedUser(u);
                et2.setEmailContentType(Constant.STARTUPS_ADMIN.toString());
                et2.setEmailTemplatesTypes(startUp);
                et2.setFooter("<p>STC</p>");
                et2.setHeader("<p>STC</p>");
                et2.setIntakeProgram(null);
                et2.setName(EmailKey.invite_startup_admin.toString());
                et2.setStatus(Constant.ACTIVE.toString());
                et2.setSubject(EmailKey.invite_startup_admin.toString());
                et2.setLanguage("en");
                emailTemplateRepository.save(et2);
                EmailTemplate welcomeEt1 = new EmailTemplate();
                welcomeEt1.setKey(EmailKey.welcome_startup_member.toString());
                welcomeEt1.setContent("<p>welcome_startup_member</p>");
                welcomeEt1.setCreatedUser(u);
                welcomeEt1.setEmailContentType(Constant.STARTUPS_MEMBER.toString());
                welcomeEt1.setEmailTemplatesTypes(startUp);
                welcomeEt1.setFooter("<p>STC</p>");
                welcomeEt1.setHeader("<p>STC</p>");
                welcomeEt1.setIntakeProgram(null);
                welcomeEt1.setName(EmailKey.welcome_startup_member.toString());
                welcomeEt1.setStatus(Constant.ACTIVE.toString());
                welcomeEt1.setSubject(EmailKey.welcome_startup_member.toString());
                welcomeEt1.setLanguage("en");
                emailTemplateRepository.save(welcomeEt1);
                EmailTemplate welcomeEt2 = new EmailTemplate();
                welcomeEt2.setKey(EmailKey.welcome_startup_admin.toString());
                welcomeEt2.setContent("<p>welcome_startup_admin</p>");
                welcomeEt2.setCreatedUser(u);
                welcomeEt2.setEmailContentType(Constant.STARTUPS_ADMIN.toString());
                welcomeEt2.setEmailTemplatesTypes(startUp);
                welcomeEt2.setFooter("<p>STC</p>");
                welcomeEt2.setHeader("<p>STC</p>");
                welcomeEt2.setIntakeProgram(null);
                welcomeEt2.setName(EmailKey.welcome_startup_admin.toString());
                welcomeEt2.setStatus(Constant.ACTIVE.toString());
                welcomeEt2.setSubject(EmailKey.welcome_startup_admin.toString());
                welcomeEt2.setLanguage("en");
                emailTemplateRepository.save(welcomeEt2);
                EmailTemplate et3 = new EmailTemplate();
                et3.setKey(EmailKey.general_notification.toString());
                et3.setContent("<p>general_notification</p>");
                et3.setCreatedUser(u);
                et3.setEmailContentType(Constant.GENERAL.toString());
                et3.setEmailTemplatesTypes(others);
                et3.setFooter("<p>STC</p>");
                et3.setHeader("<p>STC</p>");
                et3.setIntakeProgram(null);
                et3.setName(EmailKey.general_notification.toString());
                et3.setStatus(Constant.ACTIVE.toString());
                et3.setSubject(EmailKey.general_notification.toString());
                et3.setLanguage("en");
                emailTemplateRepository.save(et3);
                EmailTemplate startupet = new EmailTemplate();
                startupet.setKey(EmailKey.on_due_diligence_file_upload.toString());
                startupet.setContent("<p>on_due_diligence_file_upload</p>");
                startupet.setCreatedUser(u);
                startupet.setEmailContentType(Constant.GENERAL.toString());
                startupet.setEmailTemplatesTypes(others);
                startupet.setFooter("<p>STC</p>");
                startupet.setHeader("<p>STC</p>");
                startupet.setIntakeProgram(null);
                startupet.setName(EmailKey.on_due_diligence_file_upload.toString());
                startupet.setStatus(Constant.ACTIVE.toString());
                startupet.setSubject(EmailKey.on_due_diligence_file_upload.toString());
                startupet.setLanguage("en");
                emailTemplateRepository.save(startupet);
                EmailTemplate startupet11 = new EmailTemplate();
                startupet11.setKey(EmailKey.on_due_diligence_reject.toString());
                startupet11.setContent("<p>on_due_diligence_reject</p>");
                startupet11.setCreatedUser(u);
                startupet11.setEmailContentType(Constant.GENERAL.toString());
                startupet11.setEmailTemplatesTypes(others);
                startupet11.setFooter("<p>STC</p>");
                startupet11.setHeader("<p>STC</p>");
                startupet11.setIntakeProgram(null);
                startupet11.setName(EmailKey.on_due_diligence_reject.toString());
                startupet11.setStatus(Constant.ACTIVE.toString());
                startupet11.setSubject(EmailKey.on_due_diligence_reject.toString());
                startupet11.setLanguage("en");
                emailTemplateRepository.save(startupet11);
                EmailTemplate et14 = new EmailTemplate();
                et14.setKey(EmailKey.invite_management_admin.toString());
                et14.setContent("<p>invite_management_admin</p>");
                et14.setCreatedUser(u);
                et14.setEmailContentType(Constant.MANAGEMENT_TEAM_ADMIN.toString());
                et14.setEmailTemplatesTypes(mngt);
                et14.setFooter("<p>STC</p>");
                et14.setHeader("<p>STC</p>");
                et14.setIntakeProgram(null);
                et14.setName(EmailKey.invite_management_admin.toString());
                et14.setStatus(Constant.ACTIVE.toString());
                et14.setSubject(EmailKey.invite_management_admin.toString());
                et14.setLanguage("en");
                emailTemplateRepository.save(et14);
                EmailTemplate et15 = new EmailTemplate();
                et15.setKey(EmailKey.invite_management_member.toString());
                et15.setContent("<p>invite_management_member</p>");
                et15.setCreatedUser(u);
                et15.setEmailContentType(Constant.MANAGEMENT_TEAM_MEMBER.toString());
                et15.setEmailTemplatesTypes(mngt);
                et15.setFooter("<p>STC</p>");
                et15.setHeader("<p>STC</p>");
                et15.setIntakeProgram(null);
                et15.setName(EmailKey.invite_management_member.toString());
                et15.setStatus(Constant.ACTIVE.toString());
                et15.setSubject(EmailKey.invite_management_member.toString());
                et15.setLanguage("en");
                emailTemplateRepository.save(et15);
                EmailTemplate et11 = new EmailTemplate();
                et11.setKey(EmailKey.invite_coachs_and_trainers.toString());
                et11.setContent("<p>invite_coachs_and_trainers</p>");
                et11.setCreatedUser(u);
                et11.setEmailContentType(Constant.COACHES_AND_TRAINERS.toString());
                et11.setEmailTemplatesTypes(mngt);
                et11.setFooter("<p>STC</p>");
                et11.setHeader("<p>STC</p>");
                et11.setIntakeProgram(null);
                et11.setName(EmailKey.invite_coachs_and_trainers.toString());
                et11.setStatus(Constant.ACTIVE.toString());
                et11.setSubject(EmailKey.invite_coachs_and_trainers.toString());
                et11.setLanguage("en");
                emailTemplateRepository.save(et11);
                EmailTemplate et10 = new EmailTemplate();
                et10.setKey(EmailKey.invite_stc_judge.toString());
                et10.setContent("<p>invite_stc_judge</p>");
                et10.setCreatedUser(u);
                et10.setEmailContentType(Constant.STC_JUDGES.toString());
                et10.setEmailTemplatesTypes(mngt);
                et10.setFooter("<p>STC</p>");
                et10.setHeader("<p>STC</p>");
                et10.setIntakeProgram(null);
                et10.setName(EmailKey.invite_stc_judge.toString());
                et10.setStatus(Constant.ACTIVE.toString());
                et10.setSubject(EmailKey.invite_stc_judge.toString());
                et10.setLanguage("en");
                emailTemplateRepository.save(et10);
                EmailTemplate et13 = new EmailTemplate();
                et13.setKey(EmailKey.invite_non_stc_judge.toString());
                et13.setContent("<p>invite_non_stc_judge</p>");
                et13.setCreatedUser(u);
                et13.setEmailContentType(Constant.NON_STC_JUDGES.toString());
                et13.setEmailTemplatesTypes(mngt);
                et13.setFooter("<p>STC</p>");
                et13.setHeader("<p>STC</p>");
                et13.setIntakeProgram(null);
                et13.setName(EmailKey.invite_non_stc_judge.toString());
                et13.setStatus(Constant.ACTIVE.toString());
                et13.setSubject(EmailKey.invite_non_stc_judge.toString());
                et13.setLanguage("en");
                emailTemplateRepository.save(et13);
                EmailTemplate et12 = new EmailTemplate();
                et12.setKey(EmailKey.receptionist.toString());
                et12.setContent("<p>receptionist</p>");
                et12.setCreatedUser(u);
                et12.setEmailContentType(Constant.RECEPTIONIST.toString());
                et12.setEmailTemplatesTypes(mngt);
                et12.setFooter("<p>STC</p>");
                et12.setHeader("<p>STC</p>");
                et12.setIntakeProgram(null);
                et12.setName(EmailKey.receptionist.toString());
                et12.setStatus(Constant.ACTIVE.toString());
                et12.setSubject(EmailKey.receptionist.toString());
                et12.setLanguage("en");
                emailTemplateRepository.save(et12);
                EmailTemplate welcomeEt14 = new EmailTemplate();
                welcomeEt14.setKey(EmailKey.welcome_management_admin.toString());
                welcomeEt14.setContent("<p>welcome_management_admin</p>");
                welcomeEt14.setCreatedUser(u);
                welcomeEt14.setEmailContentType(Constant.MANAGEMENT_TEAM_ADMIN.toString());
                welcomeEt14.setEmailTemplatesTypes(mngt);
                welcomeEt14.setFooter("<p>STC</p>");
                welcomeEt14.setHeader("<p>STC</p>");
                welcomeEt14.setIntakeProgram(null);
                welcomeEt14.setName(EmailKey.welcome_management_admin.toString());
                welcomeEt14.setStatus(Constant.ACTIVE.toString());
                welcomeEt14.setSubject(EmailKey.welcome_management_admin.toString());
                welcomeEt14.setLanguage("en");
                emailTemplateRepository.save(welcomeEt14);
                EmailTemplate welcomeEt15 = new EmailTemplate();
                welcomeEt15.setKey(EmailKey.welcome_management_member.toString());
                welcomeEt15.setContent("<p>welcome_management_member</p>");
                welcomeEt15.setCreatedUser(u);
                welcomeEt15.setEmailContentType(Constant.MANAGEMENT_TEAM_MEMBER.toString());
                welcomeEt15.setEmailTemplatesTypes(mngt);
                welcomeEt15.setFooter("<p>STC</p>");
                welcomeEt15.setHeader("<p>STC</p>");
                welcomeEt15.setIntakeProgram(null);
                welcomeEt15.setName(EmailKey.welcome_management_member.toString());
                welcomeEt15.setStatus(Constant.ACTIVE.toString());
                welcomeEt15.setSubject(EmailKey.welcome_management_member.toString());
                welcomeEt15.setLanguage("en");
                emailTemplateRepository.save(welcomeEt15);
                EmailTemplate welcomeEt11 = new EmailTemplate();
                welcomeEt11.setKey(EmailKey.welcome_coachs_and_trainers.toString());
                welcomeEt11.setContent("<p>welcome_coachs_and_trainers</p>");
                welcomeEt11.setCreatedUser(u);
                welcomeEt11.setEmailContentType(Constant.COACHES_AND_TRAINERS.toString());
                welcomeEt11.setEmailTemplatesTypes(mngt);
                welcomeEt11.setFooter("<p>STC</p>");
                welcomeEt11.setHeader("<p>STC</p>");
                welcomeEt11.setIntakeProgram(null);
                welcomeEt11.setName(EmailKey.welcome_coachs_and_trainers.toString());
                welcomeEt11.setStatus(Constant.ACTIVE.toString());
                welcomeEt11.setSubject(EmailKey.welcome_coachs_and_trainers.toString());
                welcomeEt11.setLanguage("en");
                emailTemplateRepository.save(welcomeEt11);
                EmailTemplate welcomeEt10 = new EmailTemplate();
                welcomeEt10.setKey(EmailKey.welcome_stc_judge.toString());
                welcomeEt10.setContent("<p>welcome_stc_judge</p>");
                welcomeEt10.setCreatedUser(u);
                welcomeEt10.setEmailContentType(Constant.STC_JUDGES.toString());
                welcomeEt10.setEmailTemplatesTypes(mngt);
                welcomeEt10.setFooter("<p>STC</p>");
                welcomeEt10.setHeader("<p>STC</p>");
                welcomeEt10.setIntakeProgram(null);
                welcomeEt10.setName(EmailKey.welcome_stc_judge.toString());
                welcomeEt10.setStatus(Constant.ACTIVE.toString());
                welcomeEt10.setSubject(EmailKey.welcome_stc_judge.toString());
                welcomeEt10.setLanguage("en");
                emailTemplateRepository.save(welcomeEt10);
                EmailTemplate welcomeEt13 = new EmailTemplate();
                welcomeEt13.setKey(EmailKey.welcome_non_stc_judge.toString());
                welcomeEt13.setContent("<p>welcome_non_stc_judge</p>");
                welcomeEt13.setCreatedUser(u);
                welcomeEt13.setEmailContentType(Constant.NON_STC_JUDGES.toString());
                welcomeEt13.setEmailTemplatesTypes(mngt);
                welcomeEt13.setFooter("<p>STC</p>");
                welcomeEt13.setHeader("<p>STC</p>");
                welcomeEt13.setIntakeProgram(null);
                welcomeEt13.setName(EmailKey.welcome_non_stc_judge.toString());
                welcomeEt13.setStatus(Constant.ACTIVE.toString());
                welcomeEt13.setSubject(EmailKey.welcome_non_stc_judge.toString());
                welcomeEt13.setLanguage("en");
                emailTemplateRepository.save(welcomeEt13);
                EmailTemplate et8 = new EmailTemplate();
                et8.setKey(EmailKey.forgot_password.toString());
                et8.setContent("<p>forgot_password</p>");
                et8.setCreatedUser(u);
                et8.setEmailContentType(Constant.GENERAL.toString());
                et8.setEmailTemplatesTypes(others);
                et8.setFooter("<p>STC</p>");
                et8.setHeader("<p>STC</p>");
                et8.setIntakeProgram(null);
                et8.setName(EmailKey.forgot_password.toString());
                et8.setStatus(Constant.ACTIVE.toString());
                et8.setSubject(EmailKey.forgot_password.toString());
                et8.setLanguage("en");
                emailTemplateRepository.save(et8);
                EmailTemplate et9 = new EmailTemplate();
                et9.setKey(EmailKey.reset_password.toString());
                et9.setContent("<p>reset_password</p>");
                et9.setCreatedUser(u);
                et9.setEmailContentType(Constant.GENERAL.toString());
                et9.setEmailTemplatesTypes(others);
                et9.setFooter("<p>STC</p>");
                et9.setHeader("<p>STC</p>");
                et9.setIntakeProgram(null);
                et9.setName(EmailKey.reset_password.toString());
                et9.setStatus(Constant.ACTIVE.toString());
                et9.setSubject(EmailKey.reset_password.toString());
                et9.setLanguage("en");
                emailTemplateRepository.save(et9);
                EmailTemplate otherEt10 = new EmailTemplate();
                otherEt10.setKey(EmailKey.registration_form_submitted.toString());
                otherEt10.setContent("<p>registration_form_submitted</p>");
                otherEt10.setCreatedUser(u);
                otherEt10.setEmailContentType(Constant.GENERAL.toString());
                otherEt10.setEmailTemplatesTypes(others);
                otherEt10.setFooter("<p>STC</p>");
                otherEt10.setHeader("<p>STC</p>");
                otherEt10.setIntakeProgram(null);
                otherEt10.setName(EmailKey.registration_form_submitted.toString());
                otherEt10.setStatus(Constant.ACTIVE.toString());
                otherEt10.setSubject(EmailKey.registration_form_submitted.toString());
                otherEt10.setLanguage("en");
                emailTemplateRepository.save(otherEt10);
                EmailTemplate otheret11 = new EmailTemplate();
                otheret11.setKey(EmailKey.selected_for_assessment.toString());
                otheret11.setContent("<p>selected_for_assessment</p>");
                otheret11.setCreatedUser(u);
                otheret11.setEmailContentType(Constant.GENERAL.toString());
                otheret11.setEmailTemplatesTypes(others);
                otheret11.setFooter("<p>STC</p>");
                otheret11.setHeader("<p>STC</p>");
                otheret11.setIntakeProgram(null);
                otheret11.setName(EmailKey.selected_for_assessment.toString());
                otheret11.setStatus(Constant.ACTIVE.toString());
                otheret11.setSubject(EmailKey.selected_for_assessment.toString());
                otheret11.setLanguage("en");
                emailTemplateRepository.save(otheret11);
                EmailTemplate otheret111 = new EmailTemplate();
                otheret111.setKey(EmailKey.assigned_to_assessment_judges.toString());
                otheret111.setContent("<p>assigned_to_assessment_judges</p>");
                otheret111.setCreatedUser(u);
                otheret111.setEmailContentType(Constant.GENERAL.toString());
                otheret111.setEmailTemplatesTypes(others);
                otheret111.setFooter("<p>STC</p>");
                otheret111.setHeader("<p>STC</p>");
                otheret111.setIntakeProgram(null);
                otheret111.setName(EmailKey.assigned_to_assessment_judges.toString());
                otheret111.setStatus(Constant.ACTIVE.toString());
                otheret111.setSubject(EmailKey.assigned_to_assessment_judges.toString());
                otheret111.setLanguage("en");
                emailTemplateRepository.save(otheret111);
                EmailTemplate otheret112 = new EmailTemplate();
                otheret112.setKey(EmailKey.assigned_to_bootcamp_judges.toString());
                otheret112.setContent("<p>assigned_to_bootcamp_judges</p>");
                otheret112.setCreatedUser(u);
                otheret112.setEmailContentType(Constant.GENERAL.toString());
                otheret112.setEmailTemplatesTypes(others);
                otheret112.setFooter("<p>STC</p>");
                otheret112.setHeader("<p>STC</p>");
                otheret112.setIntakeProgram(null);
                otheret112.setName(EmailKey.assigned_to_bootcamp_judges.toString());
                otheret112.setStatus(Constant.ACTIVE.toString());
                otheret112.setSubject(EmailKey.assigned_to_bootcamp_judges.toString());
                otheret112.setLanguage("en");
                emailTemplateRepository.save(otheret112);
                EmailTemplate otherEt12 = new EmailTemplate();
                otherEt12.setKey(EmailKey.not_selected_for_assessment.toString());
                otherEt12.setContent("<p>not_selected_for_assessment</p>");
                otherEt12.setCreatedUser(u);
                otherEt12.setEmailContentType(Constant.GENERAL.toString());
                otherEt12.setEmailTemplatesTypes(others);
                otherEt12.setFooter("<p>STC</p>");
                otherEt12.setHeader("<p>STC</p>");
                otherEt12.setIntakeProgram(null);
                otherEt12.setName(EmailKey.not_selected_for_assessment.toString());
                otherEt12.setStatus(Constant.ACTIVE.toString());
                otherEt12.setSubject(EmailKey.not_selected_for_assessment.toString());
                otherEt12.setLanguage("en");
                emailTemplateRepository.save(otherEt12);
                EmailTemplate otherEt13 = new EmailTemplate();
                otherEt13.setKey(EmailKey.selected_for_bootcamp.toString());
                otherEt13.setContent("<p>selected_for_bootcamp</p>");
                otherEt13.setCreatedUser(u);
                otherEt13.setEmailContentType(Constant.GENERAL.toString());
                otherEt13.setEmailTemplatesTypes(others);
                otherEt13.setFooter("<p>STC</p>");
                otherEt13.setHeader("<p>STC</p>");
                otherEt13.setIntakeProgram(null);
                otherEt13.setName(EmailKey.selected_for_bootcamp.toString());
                otherEt13.setStatus(Constant.ACTIVE.toString());
                otherEt13.setSubject(EmailKey.selected_for_bootcamp.toString());
                otherEt13.setLanguage("en");
                emailTemplateRepository.save(otherEt13);
                EmailTemplate otherEt14 = new EmailTemplate();
                otherEt14.setKey(EmailKey.not_selected_for_bootcamp.toString());
                otherEt14.setContent("<p>not_selected_for_bootcamp</p>");
                otherEt14.setCreatedUser(u);
                otherEt14.setEmailContentType(Constant.GENERAL.toString());
                otherEt14.setEmailTemplatesTypes(others);
                otherEt14.setFooter("<p>STC</p>");
                otherEt14.setHeader("<p>STC</p>");
                otherEt14.setIntakeProgram(null);
                otherEt14.setName(EmailKey.not_selected_for_bootcamp.toString());
                otherEt14.setStatus(Constant.ACTIVE.toString());
                otherEt14.setSubject(EmailKey.not_selected_for_bootcamp.toString());
                otherEt14.setLanguage("en");
                emailTemplateRepository.save(otherEt14);
                EmailTemplate otherEt15 = new EmailTemplate();
                otherEt15.setKey(EmailKey.on_onboarding.toString());
                otherEt15.setContent("<p>on_onboarding</p>");
                otherEt15.setCreatedUser(u);
                otherEt15.setEmailContentType(Constant.GENERAL.toString());
                otherEt15.setEmailTemplatesTypes(others);
                otherEt15.setFooter("<p>STC</p>");
                otherEt15.setHeader("<p>STC</p>");
                otherEt15.setIntakeProgram(null);
                otherEt15.setName(EmailKey.on_onboarding.toString());
                otherEt15.setStatus(Constant.ACTIVE.toString());
                otherEt15.setSubject(EmailKey.on_onboarding.toString());
                otherEt15.setLanguage("en");
                emailTemplateRepository.save(otherEt15);
                EmailTemplate otherEt16 = new EmailTemplate();
                otherEt16.setKey(EmailKey.on_due_diligence_approve.toString());
                otherEt16.setContent("<p>on_due_diligence_approve</p>");
                otherEt16.setCreatedUser(u);
                otherEt16.setEmailContentType(Constant.GENERAL.toString());
                otherEt16.setEmailTemplatesTypes(others);
                otherEt16.setFooter("<p>STC</p>");
                otherEt16.setHeader("<p>STC</p>");
                otherEt16.setIntakeProgram(null);
                otherEt16.setName(EmailKey.on_due_diligence_approve.toString());
                otherEt16.setStatus(Constant.ACTIVE.toString());
                otherEt16.setSubject(EmailKey.on_due_diligence_approve.toString());
                otherEt16.setLanguage("en");
                emailTemplateRepository.save(otherEt16);
                EmailTemplate otherEt161 = new EmailTemplate();
                otherEt161.setKey(EmailKey.user_unblocked.toString());
                otherEt161.setContent("<p>user_unblocked</p>");
                otherEt161.setCreatedUser(u);
                otherEt161.setEmailContentType(Constant.GENERAL.toString());
                otherEt161.setEmailTemplatesTypes(others);
                otherEt161.setFooter("<p>STC</p>");
                otherEt161.setHeader("<p>STC</p>");
                otherEt161.setIntakeProgram(null);
                otherEt161.setName(EmailKey.user_unblocked.toString());
                otherEt161.setStatus(Constant.ACTIVE.toString());
                otherEt161.setSubject(EmailKey.user_unblocked.toString());
                otherEt161.setLanguage("en");
                emailTemplateRepository.save(otherEt161);
                EmailTemplate otherEt1611 = new EmailTemplate();
                otherEt1611.setKey(EmailKey.on_due_dligence_file_upload.toString());
                otherEt1611.setContent("<p>on_due_dligence_file_upload</p>");
                otherEt1611.setCreatedUser(u);
                otherEt1611.setEmailContentType(Constant.GENERAL.toString());
                otherEt1611.setEmailTemplatesTypes(others);
                otherEt1611.setFooter("<p>STC</p>");
                otherEt1611.setHeader("<p>STC</p>");
                otherEt1611.setIntakeProgram(null);
                otherEt1611.setName(EmailKey.on_due_dligence_file_upload.toString());
                otherEt1611.setStatus(Constant.ACTIVE.toString());
                otherEt1611.setSubject(EmailKey.on_due_dligence_file_upload.toString());
                otherEt1611.setLanguage("en");
                emailTemplateRepository.save(otherEt1611);
                EmailTemplate otherEt16111 = new EmailTemplate();
                otherEt16111.setKey(EmailKey.user_blocked.toString());
                otherEt16111.setContent("<p>user_blocked</p>");
                otherEt16111.setCreatedUser(u);
                otherEt16111.setEmailContentType(Constant.GENERAL.toString());
                otherEt16111.setEmailTemplatesTypes(others);
                otherEt16111.setFooter("<p>STC</p>");
                otherEt16111.setHeader("<p>STC</p>");
                otherEt16111.setIntakeProgram(null);
                otherEt16111.setName(EmailKey.user_blocked.toString());
                otherEt16111.setStatus(Constant.ACTIVE.toString());
                otherEt16111.setSubject(EmailKey.user_blocked.toString());
                otherEt16111.setLanguage("en");
                emailTemplateRepository.save(otherEt16111);
                EmailTemplate otherEt161111 = new EmailTemplate();
                otherEt161111.setKey(EmailKey.login_otp.toString());
                otherEt161111.setContent("<p>login_otp</p>");
                otherEt161111.setCreatedUser(u);
                otherEt161111.setEmailContentType(Constant.GENERAL.toString());
                otherEt161111.setEmailTemplatesTypes(others);
                otherEt161111.setFooter("<p>STC</p>");
                otherEt161111.setHeader("<p>STC</p>");
                otherEt161111.setIntakeProgram(null);
                otherEt161111.setName(EmailKey.login_otp.toString());
                otherEt161111.setStatus(Constant.ACTIVE.toString());
                otherEt161111.setSubject(EmailKey.login_otp.toString());
                otherEt161111.setLanguage("en");
                emailTemplateRepository.save(otherEt161111);
            }
        }
    }

    @Transactional
    @Override
    public void existinIntake() {
        if (intakeProgramRepository.count() == 0) {
            IntakeProgram ip = new IntakeProgram();
            ip.setPeriodEnd(new Date());
            ip.setPeriodStart(new Date());
            ip.setProgramName(Constant.EXISTING_INTAKE.toString());
            ip.setStatus(Constant.EXISTING_INTAKE.toString());
            ip.setPhaseStatus(1);
            intakeProgramRepository.save(ip);
        }
    }
}
